export type Feeling =
  | 'calm'
  | 'courage'
  | 'compassion'
  | 'confidence'
  | 'clarity'
  | 'connection'
  | 'curiosity'
  | 'creativity';

export const FEELINGS: Feeling[] = [
  'calm',
  'courage',
  'compassion',
  'confidence',
  'clarity',
  'connection',
  'curiosity',
  'creativity',
];

/** One-line intent shown under each category title. */
export const CATEGORY_INTENT: Record<Feeling, string> = {
  calm: 'For signaling safety, softening stress, and downshifting fight-or-flight.',
  courage: 'For mobilizing energy, facing fear, and taking one brave step.',
  compassion: 'For burnout, self-kindness, recovery, and inner softness.',
  confidence:
    'For lifting shutdown, rebuilding self-trust, and restoring inner power.',
  clarity: 'For mental overload, overthinking, focus, and wise next steps.',
  connection:
    'For loneliness, co-regulation, belonging, and emotional support.',
  curiosity:
    'For shifting out of fear, softening control, and opening the mind.',
  creativity:
    'For emotional expression, possibility, play, and moving stuck energy.',
};

/**
 * Phobik Affirmation Library — 8 categories × 25 affirmations.
 * Each category aligns 1:1 with a Daily-Flow emotional family via
 * {@link EMOTIONAL_FAMILY_TO_FEELING}.
 */
export const AFFIRMATIONS: Record<Feeling, string[]> = {
  calm: [
    'I am safe in this moment.',
    'I am allowed to slow down.',
    'I am breathing myself back to balance.',
    'I am supported by the ground beneath me.',
    'I am releasing tension one breath at a time.',
    'I am teaching my body that this moment is safe.',
    'I am safe even when life feels uncertain.',
    'I am allowing my nervous system to soften.',
    'I am creating space for calm.',
    'I am returning to myself.',
    'I am more than this feeling.',
    'I am grounded in the present moment.',
    'I am letting my shoulders relax.',
    'I am giving my body permission to rest.',
    'I am moving from survival into safety.',
    'I am breathing slower than my stress.',
    'I am finding peace in this moment.',
    'I am relaxing into what is.',
    'I am allowing calm to find me.',
    'I am safe enough to let go.',
    'I am welcoming ease into my body.',
    'I am choosing softness over struggle.',
    'I am settling into the present.',
    'I am becoming more regulated with every breath.',
    'I am at home within myself.',
  ],
  courage: [
    'I am capable of taking one brave step.',
    'I am stronger than this moment of fear.',
    'I am learning that discomfort is not danger.',
    'I am growing through what I face.',
    'I am building courage through action.',
    'I am willing to try.',
    'I am safe enough to move forward.',
    'I am trusting myself more each day.',
    'I am capable of handling uncertainty.',
    'I am moving with fear, not waiting for fear to leave.',
    'I am becoming more resilient.',
    'I am choosing progress over perfection.',
    'I am stronger than my anxious thoughts.',
    'I am expanding beyond old limits.',
    'I am brave enough to begin.',
    'I am proud of every small step.',
    'I am teaching my brain that I can do hard things.',
    'I am building confidence through repetition.',
    'I am capable of growth.',
    'I am learning to trust myself.',
    'I am bigger than this moment.',
    'I am showing up for myself today.',
    'I am facing life one step at a time.',
    'I am courageous in ways I often forget.',
    "I am becoming who fear said I couldn't be.",
  ],
  compassion: [
    'I am worthy of kindness.',
    'I am allowed to rest without earning it.',
    'I am not behind in life.',
    'I am doing the best I can with what I have.',
    'I am worthy even when I am tired.',
    'I am releasing unrealistic expectations.',
    'I am treating myself with gentleness.',
    'I am allowed to have difficult days.',
    'I am enough exactly as I am.',
    'I am learning to speak kindly to myself.',
    'I am honoring my limits.',
    'I am giving myself grace.',
    'I am more than my productivity.',
    'I am deserving of care.',
    'I am allowed to pause.',
    'I am learning to accept myself.',
    'I am not broken.',
    'I am human, and that is enough.',
    'I am letting go of self-judgment.',
    'I am meeting myself with understanding.',
    'I am worthy of compassion.',
    'I am learning to trust my needs.',
    'I am embracing progress instead of perfection.',
    'I am allowed to recover.',
    'I am worthy of the same love I give others.',
  ],
  confidence: [
    'I am waking up my energy.',
    'I am capable of taking action.',
    'I am stronger than exhaustion wants me to believe.',
    'I am reconnecting with my strength.',
    'I am building momentum.',
    'I am capable of more than I realize.',
    'I am trusting my abilities.',
    'I am reclaiming my energy.',
    'I am moving forward one step at a time.',
    'I am remembering my strengths.',
    'I am capable and resourceful.',
    'I am rebuilding trust in myself.',
    'I am becoming more confident through experience.',
    'I am choosing action over avoidance.',
    'I am reconnecting with possibility.',
    'I am creating positive momentum.',
    'I am resilient and adaptable.',
    'I am learning from every challenge.',
    'I am stronger than yesterday.',
    'I am capable of meaningful change.',
    'I am showing up for my future self.',
    'I am worthy of success and fulfillment.',
    'I am developing confidence from within.',
    'I am capable of taking the next step.',
    'I am becoming more empowered every day.',
  ],
  clarity: [
    'I am focusing on what matters most.',
    'I am releasing mental clutter.',
    'I am allowing clarity to emerge.',
    'I am simplifying my next step.',
    'I am letting go of unnecessary pressure.',
    'I am creating space in my mind.',
    'I am clear about what I need today.',
    'I am trusting my inner wisdom.',
    'I am choosing presence over overwhelm.',
    'I am focusing on one thing at a time.',
    'I am letting confusion settle.',
    'I am listening to my intuition.',
    'I am making room for insight.',
    'I am calm enough to think clearly.',
    'I am trusting the process.',
    'I am aligned with my values.',
    'I am releasing overthinking.',
    'I am finding simplicity.',
    'I am creating order from chaos.',
    'I am focusing my energy wisely.',
    'I am seeing the bigger picture.',
    'I am giving myself permission to slow down.',
    'I am creating mental space to breathe.',
    'I am connected to what truly matters.',
    'I am moving through life with intention.',
  ],
  connection: [
    'I am worthy of connection exactly as I am.',
    'I am safe to reach for support.',
    'I am allowed to be seen without being perfect.',
    'I am connected to people who care.',
    'I am opening to warmth, kindness, and belonging.',
    'I am not meant to carry everything alone.',
    'I am safe to receive help.',
    'I am building relationships one honest moment at a time.',
    'I am worthy of being understood.',
    'I am creating space for real connection.',
    'I am allowing myself to be supported.',
    'I am connected to the breath, the earth, and this moment.',
    'I am part of something larger than my fear.',
    'I am safe to let others care about me.',
    'I am choosing connection over isolation.',
    'I am softening the walls around my heart.',
    'I am worthy of healthy, steady love.',
    'I am present with myself and others.',
    'I am learning to trust safe people.',
    'I am connected even when I feel alone.',
    'I am opening my heart at my own pace.',
    'I am giving and receiving kindness today.',
    'I am safe to speak honestly.',
    'I am building belonging through small moments.',
    'I am held by the support available to me.',
  ],
  curiosity: [
    'I am curious about what this moment is teaching me.',
    'I am open to seeing this differently.',
    'I am replacing judgment with curiosity.',
    'I am learning from my nervous system.',
    'I am safe to wonder instead of worry.',
    'I am curious about what I need right now.',
    'I am exploring life one breath at a time.',
    'I am open to new possibilities.',
    'I am learning to ask gentle questions.',
    'I am curious about what helps me feel safe.',
    'I am discovering new ways to support myself.',
    'I am open to growth without pressure.',
    'I am learning from discomfort without fearing it.',
    'I am curious about the next small step.',
    'I am willing to understand myself more deeply.',
    'I am open to surprise, change, and discovery.',
    'I am allowing uncertainty to become exploration.',
    'I am interested in what is possible for me.',
    'I am learning that fear is information, not identity.',
    'I am curious about the wisdom of my body.',
    'I am approaching myself with openness.',
    'I am growing through gentle awareness.',
    'I am safe to not have all the answers today.',
    "I am discovering strength I didn't know I had.",
    'I am meeting life with an open mind and steady heart.',
  ],
  creativity: [
    'I am creative in the way I heal.',
    'I am allowed to express what I feel.',
    'I am turning stress into insight.',
    'I am open to new ways of moving through this.',
    'I am creating space for possibility.',
    'I am safe to imagine a calmer future.',
    'I am expressing myself without needing perfection.',
    'I am allowing my energy to move in healthy ways.',
    'I am turning pressure into presence.',
    'I am creating small moments of beauty today.',
    'I am open to inspiration, even in hard seasons.',
    'I am allowing my inner world to have a voice.',
    'I am free to create without judgment.',
    'I am transforming fear into growth.',
    'I am finding new paths through old patterns.',
    'I am creating calm through breath, movement, and choice.',
    'I am reconnecting with play, wonder, and imagination.',
    'I am allowed to begin before I feel ready.',
    'I am making something meaningful from this moment.',
    'I am creative, adaptable, and alive.',
    "I am open to solutions I haven't seen yet.",
    'I am letting my creativity help me feel unstuck.',
    'I am expressing my truth with courage and care.',
    'I am creating a life that feels safer in my body.',
    'I am becoming the artist of my own recovery.',
  ],
};

/**
 * Daily-Flow emotional family → affirmation category. Lets the flow surface a
 * relevant affirmation based on what the user selected on the feeling step.
 */
export const EMOTIONAL_FAMILY_TO_FEELING: Record<string, Feeling> = {
  activated: 'calm',
  heavy: 'compassion',
  mixed: 'clarity',
  grounded: 'curiosity',
  energized: 'confidence',
  connected: 'connection',
};

/** Returns all affirmations for a given feeling/category. */
export function getAffirmations(feeling: Feeling): string[] {
  return AFFIRMATIONS[feeling] ?? AFFIRMATIONS.calm;
}

/** Maps a Daily-Flow emotional family id to its affirmation category. */
export function feelingForFamily(familyId: string | undefined): Feeling {
  return (familyId && EMOTIONAL_FAMILY_TO_FEELING[familyId]) || 'calm';
}
